#!c:\users\caleb\desktop\codete~1\automa~1\automa~1\env\scripts\python.exe

import docx2txt

if __name__ == '__main__':
    import sys
    args = docx2txt.process_args()
    text = docx2txt.process(args.docx, args.img_dir)
    sys.stdout.write(text.encode('utf-8'))
